### ISSUE TITLE
No microphone on Precursor

### ISSUE THREAD

**Issue by dumblob** [betrusted-io/betrusted-wiki#10]
Because Precursor doesn't have any microphone, would you ship also something like https://www.aliexpress.com/item/32855198716.html together with Precursor to not force everybody wear a headset?

**Comment by bunnie** [comment]
The choice of microphone to use will be up to user! If they prefer to use something like that, then they are welcome to use it.

**Comment by dumblob** [comment]
Of course off-the-shelf PCB-mountable microphones are not trustworthy - but is there any other choice if the device has nothing built in? Speakers apparently are safe enough (judging based on the [Crowd Supply Precursor page](https://www.crowdsupply.com/sutajio-kosagi/precursor )).

So why not to [build an own mic](https://www.instructables.com/id/DIY-Dynamic-Microphone-W-Pre-amp/ )? (there are many other takes on DIY microphones among hifi & radio communities)

It wouldn't increase the device's cost much and would make the use of the device much more likely as currently the device **fails in the last mile** as it forces one to buy some untrustworthy mic.

I hope there is still time to change this before *Beta Custom SoC-based system for early adopters.* (taken from [Development Plan](https://betrusted.io/dev-plan/ ))  gets to production.
