### ISSUE TITLE
Entering symbols on the qwerty keyboard

### ISSUE THREAD

**Issue by psychohamster** [betrusted-io/betrusted-wiki#23]
I am clearly missing something obvious here, but how do I enter symbols like & * > < # from the keyboard? The left/right shift keys capitalize the letter (as expected) and shift sym just puts an unprintable char into the stream. I feel quite dumb, but also like I've tried a lot of key combos (including double/triple taps of shift, key, etc). 
Thanks

**Comment by bunnie** [comment]
should be a press-hold on the key for >0.5 seconds to get the alternate symbols to appear. sorry, it is not terribly intuitive, but it takes after some of the motifs used in the (now ancient history) blackberry physical keyboard UX.

**Comment by psychohamster** [comment]
Ah yes - I should have tried that. My brain must have blocked out my Blackberry days - thanks for the reminder!
