### ISSUE TITLE
Devices

### ISSUE THREAD

**Issue by stappersg** [betrusted-io/betrusted-wiki#24]
The wiki doesn't tell for which devices _betrusted-io_ is available. If it is, it should go to a more visible place.

What I'm suggesting:

## Devices
_betrusted-io_ is available for these devices:
* [precursor](https://www.crowdsupply.com/sutajio-kosagi/precursor)
* [placeholder](http://example.com/placeholder)
* another device

```text
## Devices
_betrusted-io_ is available for these devices:
* [precursor](https://www.crowdsupply.com/sutajio-kosagi/precursor)
* [placeholder](http://example.com/placeholder)
* another device
```

**Comment by bunnie** [comment]
I've added a clarifying note at the top of the wiki about the relationship of Precursor and Betrusted, hopefully that's good enough.

**Comment by stappersg** [comment]
The addition of
```text
Currently, the only hardware implementation of the project referenced in this repo is the [Precursor](https://precursor.dev) device.
```
is indeed an improvement.

Please add something like
> Those who did port `betrusted-io` to other devices, are welcome to say so.

**Comment by bunnie** [comment]
ok, I added an invitation for people to reference their ports at the top of the wiki. If the list gets long enough we can bring it to a separate page but for now I think this can do, yes?

**Comment by bunnie** [comment]
(fwiw, for now the wiki is editable by anyone with a github account - so far, no vandalism, fingers crossed)

**Comment by stappersg** [comment]
OK.
Thanks.

And thanks for reminding me that I shouldn't feed github.com.   Yeah, it feels wrong to empower people with open hardware and libre software while luring them into something they have no power at all, like github.com.
