### ISSUE TITLE
Mention how to factory reset/reset root keys

### ISSUE THREAD

**Issue by asharp** [betrusted-io/betrusted-wiki#27]
Hi,

The 'Initializing Root Keys' wiki page mentions that you can factory reset and why you might want to do that, but doesn't mention how to.

For anyone wondering, the command is
`python3 precursorupdater.py --factory-reset`

**Comment by bunnie** [comment]
There's now a page for that! Thanks for the feedback.

https://github.com/betrusted-io/betrusted-wiki/wiki/Factory-Reset
