### ISSUE TITLE
Visibility in dark places and at night

### ISSUE THREAD

**Issue by dumblob** [betrusted-io/betrusted-wiki#5]
Is it planned to have backlight for dark(er) environment conditions in all betrusted hardware variants (the one to be distributed among devs as well as the final end-user board)?

(the issue https://github.com/betrusted-io/betrusted-wiki/issues/3 discusses just the visibility and contrast in bright environments)

**Comment by bunnie** [comment]
It's got good visibility and contrast in bright environments -- the display does well in direct sunlight. Night time visibility is a problem. We are currently researching a backlight solution. It's unclear if all versions will get one. One problem is a backlight adds about 1.5mm thickness to the product, or about 25% thicker. Another is that the backlight assembly would need to be full custom and is thus very expensive to produce in small volumes, so it may not be economically viable to add it to the early runs.

**Comment by dumblob** [comment]
>One problem is a backlight adds about 1.5mm thickness to the product, or about 25% thicker.

This is interesting. One would think that an *LED (OLED, ...) foil (about 0.3 mm thick) or similar would do, but apparently not :cry:.

Would be interesting to read something about this problem on your blog or Twitter :wink:.

**Comment by bunnie** [comment]
the backlight needs to be insanely bright, similar to a typical IPS TFT, so the structure is an LED bar on the edge plus diffuser plate plus films. The diffuser plate is around 1mm thick or so.

We already tried looking into a thin rear film backlight, they aren't bright enough.

**Comment by dumblob** [comment]
>the backlight needs to be insanely bright

Hm, wouldn't expect that. That also goes against the power consumption expectations :cry:.

>We already tried looking into a thin rear film backlight, they aren't bright enough.

That's a pity. Maybe we should keep this issue open then to see what'll come out of this. On the other hand it's always better to have at least half-readable display than absolutely nothing (or vice versa something super thick with high power consumption) - I'm a person who likes really dimmed displays :wink:.

**Comment by bunnie** [comment]
I don't think the backlight is a show stopper in terms of power consumption -- it's only burning power when it's on, and as you note it can be dimmed. The brightness requirement is comparable to typical IPS TFT, so it's not a /hog/. Just, needs to be much brighter than a thin film emitter can achieve.

I think just to keep the project tidy I'll close this but it can easily be re-opened if something new comes up. thanks!

**Comment by dumblob** [comment]
I got an newsletter with [Precursor](https://www.crowdsupply.com/sutajio-kosagi/precursor ) where it seems you've solved the backlight issue somehow (I quote *Both keyboard and LCD are backlit for night-time use*). Would you describe how you solved it?

**Comment by bunnie** [comment]
it's scheduled to be discussed during the campaign in an update!
